In [1]:
import numpy as np

### 1. Matrix operations

In [2]:
A = np.array([
    [4, 2, 1],
    [0, 3, -1],
    [2, 1, 5]
])

In [4]:
det_A = np.linalg.det(A)
A_inv = np.linalg.inv(A)
eigvals, eigvecs = np.linalg.eig(A)

In [5]:
identity_check = np.allclose(A @ A_inv, np.eye(3))

In [6]:
print("Determinant:", det_A)
print("Inverse:\n", A_inv)
print("Eigenvalues:", eigvals)
print("A @ A_inv equals identity:", identity_check)

Determinant: 54.00000000000001
Inverse:
 [[ 0.2962963  -0.16666667 -0.09259259]
 [-0.03703704  0.33333333  0.07407407]
 [-0.11111111  0.          0.22222222]]
Eigenvalues: [2.23070765+0.j         4.88464618+0.58974281j 4.88464618-0.58974281j]
A @ A_inv equals identity: True


### 2. Solve linear equations
### 2x + 3y = 8
### 4x + y = 10

In [7]:
coeff = np.array([
    [2, 3],
    [4, 1]
])

b = np.array([8, 10])

solution = np.linalg.solve(coeff, b)

print("Solution [x, y]:", solution)

Solution [x, y]: [2.2 1.2]
